//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASPIRE_Measures
    {
        public int Measure_ID { get; set; }
        public string Measure_Name { get; set; }
        public string Measure_Collation { get; set; }
        public string Measure_Description { get; set; }
        public Nullable<int> Report_ID { get; set; }
        public string Galileo_Measure_Name { get; set; }
        public string Image_File_Name { get; set; }
        public Nullable<decimal> Threshold { get; set; }
        public string CMS_Measure_Number { get; set; }
        public bool Is_Published { get; set; }
        public string Domain { get; set; }
    }
}
