//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concept_Each_Header
    {
        public int MPOG_Concept_Header_ID { get; set; }
        public int MPOG_Concept_ID { get; set; }
        public Nullable<byte> Concept_Status { get; set; }
    }
}
