//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostic_LineCharts
    {
        public int Diagnostic_LineChart_ID { get; set; }
        public string Short_Display_Name { get; set; }
        public string Long_Display_Name { get; set; }
        public string Description { get; set; }
        public string Diagnostic_Procedure { get; set; }
        public int Diagnostic_Module_ID { get; set; }
        public bool Is_Percentage { get; set; }
        public bool Is_Enabled { get; set; }
        public bool Case_Drill_Down_Enabled { get; set; }
        public bool Match_Highlighting_Enabled { get; set; }
        public int Diagnostic_Priority_ID { get; set; }
        public Nullable<double> Y_Min { get; set; }
        public Nullable<double> Y_Max { get; set; }
        public Nullable<double> Failure_Theshold { get; set; }
        public Nullable<double> Passing_Theshold { get; set; }
        public Nullable<double> Over_Passing_Threshold { get; set; }
        public Nullable<double> Over_Failure_Threshold { get; set; }
        public string Numerator_Label { get; set; }
        public string Denominator_Label { get; set; }
        public Nullable<int> Grace_Months { get; set; }
    }
}
