//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enumeration
    {
        public int Section_ID { get; set; }
        public string Enumeration_Content { get; set; }
        public Nullable<int> Enumeration_ID { get; set; }
        public int auto_id { get; set; }
    }
}
