//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enumeration_Responsible_Provider
    {
        public int Responsible_Provider_ID { get; set; }
        public string Responsible_Provider_Name { get; set; }
    }
}
