//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enumeration_Measure_Type
    {
        public int Measure_Type_ID { get; set; }
        public string Measure_Type_Name { get; set; }
    }
}
