//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measure_Sections_Unpublished
    {
        public int Measure_ID { get; set; }
        public string Measure_Abbreviation { get; set; }
        public string Data_Collection_Method { get; set; }
        public string Description { get; set; }
        public Nullable<int> NQS_Domain { get; set; }
        public Nullable<int> Measure_Type { get; set; }
        public Nullable<int> Scope { get; set; }
        public string Measure_Summary { get; set; }
        public string Rationale { get; set; }
        public string Inclusions { get; set; }
        public string Exclusions { get; set; }
        public string Other_Build_Details { get; set; }
        public string Success { get; set; }
        public Nullable<decimal> Threshold { get; set; }
        public Nullable<int> Responsible_Provider { get; set; }
        public string Risk_Adjustment { get; set; }
        public string Flow_Chart { get; set; }
        public string Reference { get; set; }
        public Nullable<int> Status_ID { get; set; }
    }
}
