//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MPOG_XinyuEntities4 : DbContext
    {
        public MPOG_XinyuEntities4()
            : base("name=MPOG_XinyuEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Measure_List_Result> Measure_List()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Measure_List_Result>("Measure_List");
        }
    
        public virtual ObjectResult<Details_All_Result> Details_All(Nullable<int> measure_ID)
        {
            var measure_IDParameter = measure_ID.HasValue ?
                new ObjectParameter("Measure_ID", measure_ID) :
                new ObjectParameter("Measure_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Details_All_Result>("Details_All", measure_IDParameter);
        }
    }
}
