//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Measure_Site
    {
        [Key]
        public int Measure_ID { get; set; }

        [Required(ErrorMessage ="Please write measure")]
        public string Measure { get; set; }

        [Required(ErrorMessage = "Please write measure title")]
        public string Measure_Title { get; set; }

        [Required(ErrorMessage = "Please write your NQS Domain")]
        public string NQS_Domain { get; set; }

        [Required(ErrorMessage = "Please write measure name")]
        public string Measure_Name { get; set; }

        [Required(ErrorMessage = "Please select vbr")]
        public Nullable<bool> VBR { get; set; }

        [Required(ErrorMessage = "Please write clinical lead")]
        public string Clinical_Lead { get; set; }

        [Required(ErrorMessage = "Please write developer")]
        public string Developer { get; set; }

        [Required(ErrorMessage = "Please select measure completion statuss")]
        public Nullable<bool> Measure_Spec_Completed { get; set; }

        public Nullable<System.DateTime> Date_Published { get; set; }
    }
}
