//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPOG_Concepts
    {
        public decimal MPOG_Concept_ID { get; set; }
        public decimal MPOG_Concept_Type_ID { get; set; }
        public string concept_desc { get; set; }
        public Nullable<System.DateTime> active_from { get; set; }
        public Nullable<System.DateTime> active_to { get; set; }
        public decimal active { get; set; }
    }
}
